model:
  hidden_dim: 1024
  time_embed_dim: 64
  depth: 12
  max_period: 2.0
training:
  batch_size: 128
  batch_size_smpl: 16
  num_epochs: 5000
  learning_rate: 1e-4
  num_landmarks: 64
  num_fourier_modes: 16
  dataset:
    class_label: 3
sde:
  beta_min: 0.001
  beta_max: 20.0